services:
  - type: web
    name: noticias-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
